import { day1 } from "./days/1";
import { day2 } from "./days/2";
import { day3 } from "./days/3";
import { day4 } from "./days/4";
import { day4_2 } from "./days/4";
import { day5 } from "./days/5";
import { day6 } from "./days/6";
import { day7 } from "./days/7";
import { day8 } from "./days/8";
import { day9 } from "./days/9";
import { day10 } from "./days/10";
import { day11 } from "./days/11";

// day1(Bun.file(import.meta.dir + "/input/1.txt"));
// day2(Bun.file(import.meta.dir + "/input/2.txt"));
// day3(Bun.file(import.meta.dir + "/input/3.txt"));
// day4_2(Bun.file(import.meta.dir + "/input/4.txt"));
// day5(Bun.file(import.meta.dir + "/input/5.txt"));
// day6(Bun.file(import.meta.dir + "/input/6.txt"));
// day7(Bun.file(import.meta.dir + "/input/7.txt"));
// day8(Bun.file(import.meta.dir + "/input/8.txt"));
// day9(Bun.file(import.meta.dir + "/input/9.txt"));
// day10(Bun.file(import.meta.dir + "/input/10.txt"));
day11(Bun.file(import.meta.dir + "/input/11.txt"));
